---
title: "Darwin Core Mapping"
subtitle: "Vegetation survey data from FORMICA WP1"
author: "Sanne Govaert"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = TRUE)
```

Load libraries:

```{r message = FALSE}
library(readxl)
library(dplyr)
library(here)
library(digest)        
library(EML)
```

# Read source data

```{r}
directory <- here::here("datasets", "fornalab-formica-wp1-vegetation", "data")
raw_data_herb <- read_excel(here::here(directory, "raw", "Vegetation survey_version37.xlsx"), sheet = "Herb")
raw_data_shrub <- read_excel(here::here(directory, "raw", "Vegetation survey_version37.xlsx"), sheet = "Shrub")
raw_data_tree <- read_excel(here::here(directory, "raw", "Vegetation survey_version37.xlsx"), sheet = "Tree")
raw_data_plot <- read_excel(here::here(directory, "raw", "Vegetation survey_version37.xlsx"), sheet = "Plot characteristics")
raw_data_digitalization <- read_excel(here::here(directory, "raw", "Vegetation survey_version37.xlsx"), sheet = "Digitalization info")
```

# Provide metadata

```{r basic metadata}
short_name <- "FORMICA_VEG"
title <- "FORMICA_VEG - Vegetation surveys along edge-to-core transects in open and dense forests in the framework of the Forest Microclimate Assessment (FORMICA) project"
description <- c(
  paste0("<i>", title, "</i> is a sampling event dataset published by Ghent University. It contains information on 125 sampling events (vegetation relevées of 3 x 3 m²) with 4159 validated occurrences of vascular plants in ancient deciduous broadleaved forests in temperate Europe. These data were collected to study understorey vegetation biodiversity and composition responses to distance to the forest edge in ancient forest stands with different management types in 45 edge-to-interior forest transects across Europe (Govaert et al., 2019, <a href=\"http://doi.org/10.1111/jvs.12844\">http://doi.org/10.1111/jvs.12844</a>). The aim was to disentangle the effects of the management type and the distance to the edge on alpha diversity of understorey plants in multiple European regions, while accounting for environmental characteristics. Issues with the dataset can be reported at https://github.com/inbo/fornalab-datasets/issues."),
"We have released this dataset to the public domain under a Creative Commons Zero waiver. If you have any questions regarding this dataset, don't hesitate to contact us via the contact information provided in the metadata or via opendata@inbo.be.",
"This sampling took place in the framework of the FORMICA project (<a href=\"https://formica.ugent.be/\">FORMICA</a>) and was funded by the European Research Council (ERC) (ERC Starting Grant FORMICA 757833). This dataset was published with technical support provided by the Research Institute for Nature and Forest (INBO)."
)
```

```{r metadata}
publisher <- "Ghent University"
update_frequency <- "notPlanned"
type <- "Samplingevent"
metadata_language <- "en"
data_language <- "en"
data_license <- "http://creativecommons.org/publicdomain/zero/1.0/legalcode"
metadata_license <- "cc0-1.0"
creators <- list(
  list(
    title = "Sanne Govaert", 
    email = "sanne.govaert@inbo.be",
    organization = "Research Institute for Nature and Forest (INBO)",
    first_name = "Sanne", 
    last_name = "Govaert", 
    orcid = "0000-0002-8939-1305"
  ),
  list(
    title = "Pieter Vangansbeke", 
    email = "pieter.vangansbeke@ugent.be",
    organization = "Forest & Nature Lab, Ghent University",
    first_name = "Pieter", 
    last_name = "Vangansbeke", 
    orcid = "0000-0002-6356-2858"
  ),
    list(
    title = "Camille Meeussen", 
    email = NA_character_,
    organization = "Forest & Nature Lab, Ghent University",
    first_name = "Camille", 
    last_name = "Meeussen", 
    orcid = "0000-0002-5869-4936"
  ),
    list(
    title = "Thomas Vanneste", 
    email = "thomas.vanneste@ugent.be",
    organization = "Forest & Nature Lab, Ghent University",
    first_name = "Thomas", 
    last_name = "Vanneste", 
    orcid = "0000-0001-5296-917X"
  ),
    list(
    title = "Pieter De Frenne", 
    email = "pieter.defrenne@ugent.be",
    organization = "Forest & Nature Lab, Ghent University",
    first_name = "Pieter", 
    last_name = "De Frenne", 
    orcid = "0000-0002-8613-0943"
  )
)
metadata_provider <- purrr::keep(creators, ~ .x$title %in% c("Sanne Govaert", "Pieter Vangansbeke"))
contact <- purrr::keep(creators, ~ .x$title == "Sanne Govaert")
keywords <- c("vascular plants", "understorey herbs", "vegetation survey", "forest edges", "temperate forests", "forest structure")
begin_date <-  min(raw_data_digitalization$Date_of_survey)
end_date <- max(raw_data_digitalization$Date_of_survey)
geographic_description <- "Europe"
taxonomic_coverage <- data.frame(
  scientificName = "Plantae",
  taxonRank = "kingdom"
)
taxonomic_description <- "All vascular plants. The herb layer included all vascular species, both woody plants smaller than 1 m and non-woody plants, as well as lianas. The shrub layer was defined as all woody species with a height between 1 and 7 m and the tree layer as all trees reaching heights more than 7 m. Corylus avellana was always classified into the shrub layer, regardless of its height."
references <- list(list("Govaert S, Meeussen C, Vanneste T, et al. (2019). Edge influence on understorey plant communities depends on forest management. Journal of Vegetation Science. 2020;31:281–292. doi.org/10.1111/jvs.12844"))
```

# Create ID's and join data frames

```{r}
data_plot <-
  raw_data_plot %>%
  dplyr::left_join(raw_data_digitalization) %>%
  dplyr::mutate(
    event_id = paste("FORMICA_VEG", "PLOT", .data$Code, sep = ":"),
    parent_event_id = paste("FORMICA", "TRANSECT", substr(.data$Code, 1, 6), sep = ":")
  )

data_herb <-
  raw_data_herb %>%
  dplyr::mutate(
    event_id = paste("FORMICA_VEG", "PLOT", .data$Code, sep = ":"),
    occurrence_id = paste("UGENT:FORMICA", .data$Code, "HERB", sub(" ", "_", .data$Species_name_long), sep = ":"),
    organism_quantity_type = "% coverage of herb layer"
  )

data_shrub <-
  raw_data_shrub %>%
  dplyr::mutate(
    event_id = paste("FORMICA_VEG", "PLOT", .data$Code, sep = ":"),
    occurrence_id = paste("UGENT:FORMICA", .data$Code, "SHRUB", sub(" ", "_", .data$Species_name_long), sep = ":"),
    organism_quantity_type = "% coverage of shrub layer"
  )

data_tree <-
  raw_data_tree %>%
  dplyr::mutate(
    event_id = paste("FORMICA_VEG", "PLOT", .data$Code, sep = ":"),
    occurrence_id = paste("UGENT:FORMICA", .data$Code, "TREE", sub(" ", "_", .data$Species_name_long), sep = ":"),
    organism_quantity_type = "% coverage of tree layer"
  )

column_names <- c("occurrence_id", "Cover", "organism_quantity_type", "event_id", "Species_name_long")
data_veg <- rbind(
  data_herb[column_names], data_shrub[column_names], data_tree[column_names]
) %>% 
  arrange(event_id)

coordinates <-
  data_herb %>%
  dplyr::select(event_id, Latitude, Longitude) %>%
  dplyr::distinct()
data_plot <-
  data_plot %>%
  dplyr::left_join(coordinates, by = dplyr::join_by(event_id))
```

# Darwin core transformation

```{r dwc transformation}
event <- 
  data_plot %>% 
  dplyr::mutate(
    .keep = "none",
    type = "Event",
    language = data_language,
    license = data_license, 
    rightsHolder = publisher,
    datasetID = "", # doi of published dataset
    institutionCode = "UGent", 
    datasetName = title,
    eventID = .data$event_id,
    parentEventID = .data$parent_event_id,
    eventDate = .data$Date_of_survey,
    samplesizeValue = 9,
    sampleSizeUnit = "m2",
    habitat = "temperate forest",
    samplingProtocol = "vegetation survey",
    country = dplyr::recode(
      .data$Region,
      "PO" = "Poland",
      "GE" = "Germany",
      "BE" = "Belgium",
      "NF" = "France",
      "SW" = "Switzerland",
      "CS" = "Sweden",
      "SS" = "Sweden",
      "NO" = "Norway",
      "IT" = "Italy"
      ),
    decimalLatitude = .data$Latitude,
    decimalLongitude = .data$Longitude,
    geodeticDatum = "EPSG:4326",
    coordinateUncertaintyInMeters = 30,
  )

occurrence <-
  data_veg %>% 
  mutate(
    .keep = "none",
    language = data_language,
    type = "Event",
    license = data_license, 
    rightsHolder = publisher,
    datasetID = "", # doi of published dataset
    datasetName = title,
    basisOfRecord = "HumanObservation",
    collectionCode = "FORMICA",
    occurrenceID = .data$occurrence_id,
    organismQuantity = .data$Cover,
    organismQuantityType = .data$organism_quantity_type,
    occurrenceStatus = "present",
    eventID = .data$event_id, 
    scientificName = .data$Species_name_long,
    kingdom = "Plantae",
    taxonRank = dplyr::if_else(
      grepl("subsp.", .data$Species_name_long, fixed = TRUE), 
      "subspecies",
      "species"
    )
  )

releve <- 
  data_plot %>%
  dplyr::mutate(
    .keep = "none",
    eventID = .data$event_id,
    project = "FORMICA (Forest Microclimate Assessment)",
    coverTotalInPercentage = .data$Total_cover,
    coverTreesInPercentage = .data$Tree_cover,
    coverShrubsInPercentage	= .data$Shrub_cover,
    coverHerbsInPercentage	= .data$Vascular_plants,
    coverMossesInPercentage	= .data$Moss,
    coverLitterInPercentage = .data$Litter,
    mossesIdentified = "False",
    lichensIdentified = "False"
  )
```

## Write darwin core

```{r write dwc}
dir_export <- here::here(directory, "processed")
 if (!dir.exists(dir_export)) {
    dir.create(dir_export, recursive = TRUE)
  }
readr::write_csv(event, here::here(dir_export, "event.csv"), na = "")
readr::write_csv(occurrence, here::here(dir_export, "occurrence.csv"), na = "")
readr::write_csv(releve, here::here(dir_export, "releve.csv"), na = "")
```

# Create metadata file (eml.xml)

## Function to create contributors in EML format

```{r}
create_eml_contributors <- function(contributor_list) {
  purrr::map(contributor_list, ~ EML::set_responsibleParty(
    givenName = .$first_name,
    surName = .$last_name,
    organizationName = .$organization, # Discouraged by EML, but used by IPT
    email = .$email,
    userId = if (!is.na(.$orcid)) {
      list(directory = "https://orcid.org/", .$orcid)
    } else {
      NULL
    }
  ))
}
```

This script is based on input data above.

```{r EML transformation}
# Initiate EML
eml <- list(
  packageId = uuid::UUIDgenerate(),
  system = "uuid",
  dataset = list()
)

# Set short name and title
eml$dataset$shortName <- short_name
eml$dataset$title <- title

# Set abstract
eml$dataset$abstract$para <- description

# Set update frequency (requires a description, even if empty)
eml$dataset$maintenance <- list(
  description = list(para = ""),
  maintenanceUpdateFrequency = update_frequency
)

# Set creators
eml$dataset$creator <- create_eml_contributors(creators)

# Set contacts
eml$dataset$contact <- create_eml_contributors(contact)

# Set metadata providers
eml$dataset$metadataProvider <- create_eml_contributors(metadata_provider)

# Set keywords
eml$dataset$keywordSet <-
  list(
    list(
      keywordThesaurus = paste(
        "GBIF Dataset Type Vocabulary:",
        "http://rs.gbif.org/vocabulary/gbif/dataset_type_2015-07-10.xml"
      ),
      keyword = type
    ),
    list(
      keywordThesaurus = "n/a",
      keyword = keywords
    )
  )

# Set license
eml$dataset$intellectualRights$para <- metadata_license

# Set temporal coverage and geographicDescription
eml$dataset$coverage <-
  EML::set_coverage(
    beginDate = begin_date,
    endDate = end_date,
    geographicDescription = geographic_description
  )

# Set taxonomic coverage
eml$dataset$coverage$taxonomicCoverage <-
  list(
    taxonomicClassification =
      purrr::map(1:nrow(taxonomic_coverage), function(i) {
        current_row <- taxonomic_coverage[i, ]
        list(
          taxonRankName = current_row$taxonRank,
          taxonRankValue = current_row$scientificName
        )
      })
  )
eml$dataset$coverage$taxonomicCoverage$generalTaxonomicCoverage <- taxonomic_description # does not work

# Bibliographic citations
eml$additionalMetadata$metadata$gbif$bibliography$citation <- references
```


```{r write EML}
EML::write_eml(eml, here::here(dir_export, "eml.xml"))
```

