---
title: "Darwin Core Mapping"
subtitle: "Lepidoptera survey data from FORMICA"
author: "Sanne Govaert"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = TRUE)
```

Load libraries:

```{r message = FALSE}
library(readxl)
library(dplyr)
library(here)
library(digest)        
library(EML)
```

# Read source data

```{r}
directory <- here::here("datasets", "fornalab-formica-lepidoptera", "data")
raw_data <- read_excel(here::here(directory, "raw", "Raw moth sampling data.xlsx"), sheet = "Data")
```

# Provide metadata

```{r basic metadata}
short_name <- "FORMICA_LEPIDOPTERA"
title <- "FORMICA_LEPIDOPTERA - Lepidoptera along edge-to-core transects in open and dense forests in the framework of the FORMICA project"
abstract <- c(
  "FORMICA_LEPIDOPTERA is a sampling event dataset published by Ghent University. It contains information on 128 sampling events with 1595 validated occurrences of macro-moths in 2020. These data were gathered as part of the research conducted by Vangansebeke et al. (in preparation).
Issues with the dataset can be reported at https://github.com/inbo/fornalab-datasets/issues
We have released this dataset to the public domain under a Creative Commons Zero waiver. If you have any questions regarding this dataset, don't hesitate to contact us via the contact information provided in the metadata.
This sampling took place in the framework of the FORMICA project (www.formica.ugent.be) and was funded by the European Research Council (ERC) (ERC Starting Grant FORMICA 757833). This dataset was published with technical support provided by the Research Institute for Nature and Forest (INBO)."
)
```

```{r metadata}
publisher <- "Ghent University"
dataset_id = ""
update_frequency <- "notPlanned"
type <- "Samplingevent"
metadata_language <- "en"
data_language <- "en"
data_license <- "http://creativecommons.org/publicdomain/zero/1.0/legalcode"
metadata_license <- "cc0-1.0"
creators <- list(
  list(
    title = "Pieter Vangansbeke",
    email = "pieter.vangansbeke@ugent.be",
    organization = "Forest & Nature Lab, Ghent University",
    first_name = "Pieter",
    last_name = "Vangansbeke",
    orcid = "0000-0002-6356-2858"
  ),
  list(
    title = "Pallieter De Smedt",
    email = "pallieter.desmedt@ugent.be",
    organization = "Forest & Nature Lab, Ghent University",
    first_name = "Pallieter",
    last_name = "De Smedt",
    orcid = "0000-0002-3073-6751"
  ),
  list(
    title = "Cyr Mestdagh",
    email = NA_character_,
    organization = "Natuurpunt",
    first_name = "Cyr",
    last_name = "Mestdagh",
    orcid = NA_integer_
  ),
  list(
    title = "Pieter De Frenne",
    email = "pieter.defrenne@ugent.be",
    organization = "Forest & Nature Lab, Ghent University",
    first_name = "Pieter",
    last_name = "De Frenne",
    orcid = "0000-0002-8613-0943"
  ),
  list(
    title = "Sanne Govaert",
    email = "sanne.govaert@inbo.be",
    organization = "Research Institute for Nature and Forest (INBO)",
    first_name = "Sanne",
    last_name = "Govaert",
    orcid = "0000-0002-8939-1305"
  )
)
metadata_provider <- purrr::keep(creators, ~ .x$title %in% c("Pieter Vangansbeke", "Sanne Govaert"))
contact <- purrr::keep(creators, ~ .x$title == "Pieter Vangansbeke")
keywords <- c("Lepidoptera", "macromoths", "forest edges", "temperate forests", "forest structure")
begin_date <-  min(raw_data$Date)
end_date <- max(raw_data$Date)
geographic_description <- "Temperate forests in Belgium and Northern-France"
taxonomic_coverage <- data.frame(
  scientificName = "Lepidoptera",
  taxonRank = "order"
)
taxonomic_description <- "The sampling focus for this dataset is macro-moths, i.e., some families of generally larger sized lepidoptera such as noctuidae and geometridae."
references <- list(list(NA))
```

```{r project metadata}
project_title <- "Forest Microclimate Assessment (FORMICA)"
project_personnel <- purrr::keep(creators, ~ .x$title %in% c("Pieter De Frenne", "Pieter Vangansbeke", "Sanne Govaert"))
project_abstract <- "Microclimatic buffering of plant responses to macroclimate warming in temperate forests.
Recent global warming is acting on ecosystems across the globe and threatening biodiversity. Yet, due to slow responses, many biological communities are lagging behind warming of the macroclimate (the climate of a large geographic region). The buffering of microclimates near the ground measured in local areas, arising from terrain features such as vegetation and topography, can explain why many species are lagging behind macroclimate warming. However, almost all studies ignore the effects of microclimates and key uncertainties still exist about this mechanism.
Microclimates are particularly evident in forests, where understorey habitats are buffered by overstorey trees. In temperate forests, the understorey contains the vast majority of plant diversity and plays an essential role in driving ecosystem processes.
The overall goal of FORMICA (FORest MICroclimate Assessment) is to quantify and understand the role of microclimatic buffering in modulating forest plant responses to macroclimate warming. We apply microtemperature loggers, perform experimental heating, use fluorescent tubes and install a large-scale transplant experiment in temperate forests across Europe. The results will then be integrated in models to forecast plant diversity in temperate forests as macroclimate warms.
FORMICA is a large integrative study on microclimatic buffering of macroclimate warming in forests. The project will reshape our current understanding of the impacts of climate change on forests and help land managers and policy makers to develop urgently needed adaptation strategies."
funding <- "European Research Council (ERC) Starting Grant FORMICA 757833"
study_area_description <- "Europe"
design_description <- "Work package 1: Observatory: plant data at individual, population, species, community & ecosystem level

Global macroclimate is changing significantly, with a rise in temperature as one of the most studied trends. Less monitored though nevertheless important is the microclimate. As this microclimate can differ considerably from the macroclimate due to local terrain features or vegetation cover, it might protect plants against the consequences of climate change. Forests, which create their own unique microclimatic systems driven by the vegetation structure, can thus buffer organisms against the rising temperature. Therefore, animals and understorey plants would not have to migrate or adapt as quickly as expected.

The goal of WP1 is twofold:
- To quantify microclimatic buffering and investigate the impact of forest characteristics (tree species composition, management, structure)
- To study climate - plant performance relationships along different spatial scales

Why?

To gain more insight in the establishment of microclimates and to predict the effects of future climate change on understorey species taking into account microclimates. Further, this work package will also provide management guidelines on how to manage forest while focussing on conversation in the face of macroclimate warming.

How?

A macro- and microclimatic plot network was established across four spatial scales: (1) a latitudinal gradient from Norway to central Italy with plots in nine different regions, (2) an altitudinal gradient in three of the selected regions, (3) a management gradient and (4) and gradient from the forest edge towards the core. In addition to macro- and microclimate, the forest structure, soil and litter characteristics and the vegetation community and its functional traits were assessed."
```

# Create ID's and join data frames

```{r}
my_data <-
  raw_data %>%
  dplyr::mutate(
    transect = toupper(Transect),
    code = toupper(fullplotID),
    event_id = paste("FORMICA_LEPIDOPTERA", "PLOT", .data$code, Period, sep = ":"),
    parent_event_id = paste("FORMICA", "TRANSECT", substr(.data$code, 1, 6), sep = ":"),
    occurrence_id = paste("UGENT:FORMICA", .data$code, Period, "LEPIODOPTERA", sub(" ", "_", .data$`Species (Scientific name)`), sep = ":")
  )
```

# Darwin core transformation

```{r dwc transformation}
event <- 
  my_data %>% 
  dplyr::mutate(
    .keep = "none",
    type = "Event",
    language = data_language,
    license = data_license, 
    rightsHolder = publisher,
    datasetID = dataset_id,
    institutionCode = "UGent", 
    datasetName = title,
    eventID = .data$event_id,
    parentEventID = .data$parent_event_id,
    eventDate = .data$Date,
    habitat = "temperate forest",
    samplingProtocol = "light trapping",
    country = dplyr::if_else(
      startsWith(.data$transect, "B"),
      "Belgium",
      "France"
      ),
    decimalLatitude = .data$LAT,
    decimalLongitude = .data$LON,
    geodeticDatum = "EPSG:4326",
    coordinateUncertaintyInMeters = 30,
    eventRemarks = .data$`Remarks (Wind, rain, moon, cloudiness)`
  ) %>% 
  dplyr::distinct()

occurrence <-
  my_data %>% 
  dplyr::filter(!is.na(`Species (Scientific name)`)) %>% 
  dplyr::mutate(
    .keep = "none",
    language = data_language,
    type = "Event",
    license = data_license, 
    rightsHolder = publisher,
    datasetID = dataset_id,
    datasetName = title,
    basisOfRecord = "HumanObservation",
    collectionCode = "FORMICA",
    occurrenceID = .data$occurrence_id,
    organismQuantity = .data$Amount,
    organismQuantityType = "individuals",
    occurrenceStatus = "present",
    eventID = .data$event_id, 
    scientificName = .data$`Species (Scientific name)`,
    kingdom = "Animalia",
    taxonRank = "species"
  )
```

# Data quality check

## Check classes of columns

```{r}
# Event
inherits(event$eventDate, "POSIXct")
check_event_numeric <- c(
  "decimalLatitude",
  "decimalLongitude"
)
purrr::map(event[, check_event_numeric], is.numeric)

# Occurrence
is.numeric(occurrence$organismQuantity)
```


## Check species names with GBIF backbone

```{r}
from_gbif <-
  occurrence %>%
  select(scientificName, taxonRank) %>%
  distinct %>%
  mutate(
    lookup = purrr::map2(
      scientificName,
      taxonRank,
      ~ rgbif::name_backbone(.x, rank = .y, kingdom = "Animalia")
    ),
    .keep = "none"
  ) %>%
  dplyr::pull(lookup) %>%
  purrr::list_rbind()

## not matched exactly
no_exact_match <- unique(occurrence$scientificName)[!unique(occurrence$scientificName) %in% from_gbif$canonicalName]
from_gbif %>% filter(verbatim_name %in% no_exact_match)
```

## Write darwin core

```{r write dwc}
dir_export <- here::here(directory, "processed")
 if (!dir.exists(dir_export)) {
    dir.create(dir_export, recursive = TRUE)
  }
readr::write_csv(event, here::here(dir_export, "event.csv"), na = "")
readr::write_csv(occurrence, here::here(dir_export, "occurrence.csv"), na = "")
```

# Create metadata file (eml.xml)

## Function to create contributors in EML format

```{r}
create_eml_contributors <- function(contributor_list) {
  purrr::map(contributor_list, ~ EML::set_responsibleParty(
    givenName = .$first_name,
    surName = .$last_name,
    organizationName = .$organization, # Discouraged by EML, but used by IPT
    email = .$email,
    userId = if (!is.na(.$orcid)) {
      list(directory = "https://orcid.org/", .$orcid)
    } else {
      NULL
    }
  ))
}
```

This script is based on input data above.

```{r EML dataset}
# Set short name and title
eml$dataset$shortName <- short_name
eml$dataset$title <- title

# Set abstract
eml$dataset$abstract$para <- abstract

# Set update frequency (requires a description, even if empty)
eml$dataset$maintenance <- list(
  description = list(para = ""),
  maintenanceUpdateFrequency = update_frequency
)

# Set creators
eml$dataset$creator <- create_eml_contributors(creators)

# Set contacts
eml$dataset$contact <- create_eml_contributors(contact)

# Set metadata providers
eml$dataset$metadataProvider <- create_eml_contributors(metadata_provider)

# Set keywords
eml$dataset$keywordSet <-
  list(
    list(
      keywordThesaurus = paste(
        "GBIF Dataset Type Vocabulary:",
        "http://rs.gbif.org/vocabulary/gbif/dataset_type_2015-07-10.xml"
      ),
      keyword = type
    ),
    list(
      keywordThesaurus = "n/a",
      keyword = keywords
    )
  )

# Set license
eml$dataset$intellectualRights$para <- metadata_license

# Set temporal coverage and geographicDescription
eml$dataset$coverage <-
  EML::set_coverage(
    beginDate = begin_date,
    endDate = end_date,
    geographicDescription = geographic_description
  )

# Set taxonomic coverage
eml$dataset$coverage$taxonomicCoverage <-
  list(
    taxonomicClassification =
      purrr::map(1:nrow(taxonomic_coverage), function(i) {
        current_row <- taxonomic_coverage[i, ]
        list(
          taxonRankName = current_row$taxonRank,
          taxonRankValue = current_row$scientificName
        )
      })
  )
eml$dataset$coverage$taxonomicCoverage$generalTaxonomicCoverage <- taxonomic_description # does not work
```

```{r EML project}
eml$dataset$project$title <- project_title
eml$dataset$project$personnel <- create_eml_contributors(project_personnel)
eml$dataset$project$abstract$para <- project_abstract
eml$dataset$project$funding$para <- funding
eml$dataset$project$studyAreaDescription$descriptor$descriptorValue <- study_area_description
eml$dataset$project$designDescription$description$para <- design_description
```

```{r EML additional metadata}
# Bibliographic citations
eml$additionalMetadata$metadata$gbif$bibliography$citation <- references
```

```{r write EML}
EML::write_eml(eml, here::here(dir_export, "eml.xml"))
```